### ISSUE TITLE
Configurable ORCID or list of DOIs to check? [ENHANCEMENT]

### ISSUE THREAD

**Issue by peterjc** [rossmounce/checkmydois#5]
Currently the script has the ORCID ID hard coded. It would be great to have this as a command line option, or via an environment variable (perhaps defaulting to the current value for testing).

(I can see how this might then be used via a continuous integration service like TravisCI where the user can put in their own ORCID to the TravisCI settings, without having to modify the code in git)

**Comment by rossmounce** [comment]
Something like the below might work but I'll need to do some testing first. I might just create an additional R script for non-interactive usage. For personal usage I can imagine some might find it simpler just to hardcode in their ORCID once and forget about it. 

```
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0) {
  stop("At least one argument must be supplied (input ORCID ID).n", call.=FALSE)
} else if (length(args)==1) {
  # default output file
  args[2] = "mydois.txt"
}
```

**Comment by peterjc** [comment]
Another option is read the ORCID(s) from a file, again allows set-and-forget and would be pretty easy to use via an automated setup.

**Comment by sje30** [comment]
CC: get Lauren'ts opinion on the script!  I defer to his wisdom on these matters... @lgatto

**Comment by lgatto** [comment]
1. If you are in R, you should do things the R way. In this case have a vectorised function that will work for any number of ORCIDs. The issue of how to get a vector of (possibly many) ORCID ids is a different one that should be solved on its own, i.e. with a function that reads a file and produces the ORCIDs (as a `vector`, `data.frame`, ... depending on the file and function). These functions already exist: `read.csv`, `read_csv`, `readLines`, ...

2. This should be in a package (even for a single function) to benefit of proper documentation, testing, versioning, ... I am happy to do it.

**Comment by rossmounce** [comment]
All offers of help are welcome @lgatto . I think I may already be well out of my depth!

I do hope this code will be impactful though. I'm thinking already beyond just the personal usage to institutional and funder usage. The funder usage is especially interesting. Given a list of Wellcome Trust (or any other funder) DOIs, we could do _continuous_ monitoring, rather than just one-time spot checks of compliance. 

I'm particularly interested in building-out the continuous checking of access to hybrid OA articles, beyond just "is the DOI broken".
